services:
  animated-artworks:
    build:
      context: ./apple-music-animated-artworks
      dockerfile: Dockerfile
    image: apple-music-animated-artworks:local-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development