services:
  animated-artworks:
    container_name: apple-music-animated-artworks
    image: ghcr.io/m8tec/apple-music-animated-artworks:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CACHE_FILE_PATH=/app/data/cache_database.json
    restart: always